#!/bin/bash
#hostname
#circRNA
All_MGs_path="/media/toasty/MGs/"


# study_list=(Active_sludge_and_wastewater_microbial_communities_from_Klosterneuburg__Austria Active_sludge_microbial_communities_of_municipal_wastewater_treating_anaerobic_digesters_from_various_locations Anoxygenic_and_chlorotrophic_microbial_mat_microbial_communities_from_Yellowstone_National_Park__USA Aqueous_microbial_communities_from_the_Delaware_River_Bay_and_Chesapeake_Bay_under_freshwater_to_marine_salinity_gradient_to_study_organic_matter_cycling_in_a_time_series Coastal_salt_marsh_microbial_communities_from_the_Groves_Creek_Marsh__Skidaway_Island__Georgia Enriched_cultures_of_PCE_dechlorinating_microbial_communities_from_Ithaca__New_York__USA Enriched_soil_aggregate_microbial_communities_from_Iowa_State_university_to_study_microbial_drivers_of_carbon_cycling Extremophilic_microbial_mat_communities_from_USA_and_Mexico Freshwater_microbial_communities_amended_with_dissolved_organic_matter__DOM__from_various_rivers_in_the_United_States Freshwater_microbial_communities_from_oligotrophic__dystrophic__and_eutrophic_lakes_in_Wisconsin__USA Freshwater_sediment_methanotrophic_microbial_communities_from_Lake_Washington_under_simulated_oxygen_tension Lab_enriched_sorghum-adapted_microbial_communities_from_Joint_BioEnergy_Institute__Emeryville__California__United_States Marine_archaeal_communities_from_Monterey_Bay__CA__that_are_ammonia_oxidizing Marine_microbial_communities_from_expanding_oxygen_minimum_zones_in_the_northeastern_subarctic_Pacific_Ocean Marine_microbial_communities_from_the_Southern_Atlantic_ocean_transect_to_study_dissolved_organic_matter_and_carbon_cycling_MTs_only_low_euk Peatlands_soil_microbial_communities_from_Germany_and_Austria__that_are_sulfate_reducing Permafrost_soil_microbial_communities_from_the_Arctic__to_analyse_light_accelerated_degradation_of_dissolved_organic_matter__DOM Rhizosphere_microbial_communities_from_salt_marsh_grasses_in_Alabama__United_States Saline__thermophilic_phototrophic_and_chemotrophic_mat_microbial_communities_from_various_locations_in_USA_and_Mexico Seawater_microbial_communities_from_Monterey_Bay__California__United_States Soil_microbial_communities_from_permafrost_in_Bonanza_Creek__Alaska Subsurface_hydrocarbon_microbial_communities_from_various_worldwide_Shell_locations Grasslands_soil_microbial_communities_from_the_Angelo_Coastal_Reserve__California__USA_1 Grasslands_soil_microbial_communities_from_the_Angelo_Coastal_Reserve__California__USA_2)
for i in ${study_list[*]}
do
echo $i
mkdir /media/toasty/MGs/"$i"/
mkdir /media/toasty/MGs/"$i"/sk100/
done

cd $All_MGs_path
study_list=(Active_sludge_and_wastewater_microbial_communities_from_Klosterneuburg__Austria Active_sludge_microbial_communities_of_municipal_wastewater_treating_anaerobic_digesters_from_various_locations Anoxygenic_and_chlorotrophic_microbial_mat_microbial_communities_from_Yellowstone_National_Park__USA Aqueous_microbial_communities_from_the_Delaware_River_Bay_and_Chesapeake_Bay_under_freshwater_to_marine_salinity_gradient_to_study_organic_matter_cycling_in_a_time_series Coastal_salt_marsh_microbial_communities_from_the_Groves_Creek_Marsh__Skidaway_Island__Georgia Enriched_cultures_of_PCE_dechlorinating_microbial_communities_from_Ithaca__New_York__USA Enriched_soil_aggregate_microbial_communities_from_Iowa_State_university_to_study_microbial_drivers_of_carbon_cycling Extremophilic_microbial_mat_communities_from_USA_and_Mexico Freshwater_microbial_communities_amended_with_dissolved_organic_matter__DOM__from_various_rivers_in_the_United_States Freshwater_microbial_communities_from_oligotrophic__dystrophic__and_eutrophic_lakes_in_Wisconsin__USA Freshwater_sediment_methanotrophic_microbial_communities_from_Lake_Washington_under_simulated_oxygen_tension Grasslands_soil_microbial_communities_from_the_Angelo_Coastal_Reserve__California__USA_1 Grasslands_soil_microbial_communities_from_the_Angelo_Coastal_Reserve__California__USA_2 Lab_enriched_sorghum-adapted_microbial_communities_from_Joint_BioEnergy_Institute__Emeryville__California__United_States Marine_archaeal_communities_from_Monterey_Bay__CA__that_are_ammonia_oxidizing Marine_microbial_communities_from_expanding_oxygen_minimum_zones_in_the_northeastern_subarctic_Pacific_Ocean Marine_microbial_communities_from_the_Southern_Atlantic_ocean_transect_to_study_dissolved_organic_matter_and_carbon_cycling_MTs_only_low_euk Peatlands_soil_microbial_communities_from_Germany_and_Austria__that_are_sulfate_reducing Permafrost_soil_microbial_communities_from_the_Arctic__to_analyse_light_accelerated_degradation_of_dissolved_organic_matter__DOM Rhizosphere_microbial_communities_from_salt_marsh_grasses_in_Alabama__United_States Saline__thermophilic_phototrophic_and_chemotrophic_mat_microbial_communities_from_various_locations_in_USA_and_Mexico Seawater_microbial_communities_from_Monterey_Bay__California__United_States Soil_microbial_communities_from_permafrost_in_Bonanza_Creek__Alaska Subsurface_hydrocarbon_microbial_communities_from_various_worldwide_Shell_locations)
for i in ${study_list[*]}
do
echo $i
blastdbcmd -db  /media/toasty/MGs/"$i"/sk100/sk100_db -entry all  -out  /media/toasty/MGs/"$i"/sk100/sk100_db.fasta
done >  /media/toasty/log.13.042021.txt



##### Serverside #####
All_MGs_path="/urigo/urineri/RNA_Viruses/V2/input/unter_mgs/"
study_list=(Grasslands_soil_microbial_communities_from_the_Angelo_Coastal_Reserve__California__USA_1 Grasslands_soil_microbial_communities_from_the_Angelo_Coastal_Reserve__California__USA_2)

for i in ${study_list[*]}
do
echo $i
scp -r   "$All_MGs_path"/"$i"/sk100/ neri@132.66.46.64:/media/toasty/MGs/"$i"/sk100/
done



All_MGs_path="/media/toasty/MGs/"
cd $All_MGs_path
mkdir tmp
mmseqs easy-linclust */*/*/sk100_db.fasta DNAome.clu tmp --min-seq-id 0.95 -c 0.95 --cov-mode 1 --kmer-per-seq-scale 0.4  --threads 6 --compressed 1   --split-memory-limit 16G