<template>
  <div>
    <TheHeader>{{ $route.params.id }}</TheHeader>
    <div class="mt-5">
      <!-- <SeqTable :metadata="metadata"></SeqTable> -->
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-8">
        <div>
          <Card title="Circular Alignment" subtitle="Generated by CSA">
            <ClientOnly>
              <StorageImage
                class="w-full"
                :src="`cluster-csa/${identity}/Cls.${clusterNumber}-CircularAlignment.bmp`"
              />
            </ClientOnly>
          </Card>
        </div>
        <div>
          <Card
            title="Blocks"
            subtitle="Which aligned sequence regions are where"
          >
            <ClientOnly>
              <StorageImage
                class="w-full"
                :src="`cluster-csa/${identity}/Cls.${clusterNumber}-Blocks.bmp`"
              />
            </ClientOnly>
          </Card>
        </div>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  data() {
    return { metadata: [{}] }
  },
  computed: {
    clusterNumber(): string {
      return this.$route.params.id.split('.').pop() ?? ''
    },
    identity(): string {
      return this.$route.params.id.split('.').slice(-2, -1)[0].slice(2)
    },
  },
  // async fetch() {this.metadata = await this.$fire.firestore.collection("sequences").where("")},
})
</script>
