<template>
  <div>
    <TheHeader>{{ clusterId }}</TheHeader>
    <div class="mt-5">
      <div class="grid grid-cols-1 lg:grid-cols-2 gap-8 mt-8">
        <ClientOnly>
          <MsaView
            :cluster-id="clusterId"
            class="col-span-1 lg:col-span-2"
          ></MsaView>
        </ClientOnly>
        <div class="col-span-1">
          <ClientOnly>
            <Card title="Circular Alignment" subtitle="Generated by CSA">
              <StorageImage
                class="w-full"
                :src="`/bmp/${releaseDate}/ID${identity}/Cls_ID${identity}_${clusterNumber}-CircularAlignment.bmp`"
              />
            </Card>
          </ClientOnly>
        </div>
        <div class="col-span-1">
          <ClientOnly>
            <Card
              title="Blocks"
              subtitle="Which aligned sequence regions are where"
            >
              <StorageImage
                class="w-full"
                :src="`/bmp/${releaseDate}/ID${identity}/Cls_ID${identity}_${clusterNumber}-Blocks.bmp`"
              />
            </Card>
          </ClientOnly>
        </div>
      </div>
      <SeqTable :metadata="metadata" class="mt-8"></SeqTable>
      <div v-if="!$fetchState.pending" class="flex justify-center mt-6">
        <LoadMore
          @click="
            maxDisplay += 50
            $fetch()
          "
        >
        </LoadMore>
      </div>
    </div>
  </div>
</template>
<script lang="ts">
import Vue from 'vue'
export default Vue.extend({
  middleware({ route, redirect }) {
    // If the user is not authenticated
    if (route.params.id.toUpperCase() !== route.params.id) {
      return redirect('/clusters/' + route.params.id.toUpperCase())
    }
  },
  data() {
    return { metadata: [{}], maxDisplay: 50 }
  },
  async fetch() {
    this.metadata = (
      await this.$fire.firestore
        .collection('sequences')
        .where('Cls_ID' + this.identity, '==', this.clusterId)
        .limit(this.maxDisplay)
        .get()
    ).docs.map((doc) => doc.data())
  },
  computed: {
    clusterId(): string {
      return this.$route.params.id.toUpperCase()
    },
    releaseDate(): string {
      return this.clusterId.slice(0, 10)
    },
    clusterNumber(): string {
      return this.clusterId.split('-').pop() ?? ''
    },
    identity(): string {
      return this.clusterId.split('-').slice(-2, -1)[0].slice(2)
    },
  },
})
</script>
